### ISSUE TITLE
Please add Java 16 support

### ISSUE THREAD

**Issue by steve4744** [AlessioDP/Parties#114]
Hi, as Paper is soon to require Java 16, and Mojang have started using Java 16 with snapshot 21w19a, I decided to update my server to use the same. Using Paper or Spigot 1.16.5 and Parties 3.0.4 I get the error below on startup
```
[23:51:59] [Server thread/INFO]: [Parties] Enabling Parties v3.0.4
[23:51:59] [Server thread/ERROR]: Error occurred while enabling Parties v3.0.4 (Is it up to date?)
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @faf4b0f
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at com.alessiodp.parties.core.common.addons.external.libby.classloader.URLClassLoaderHelper.<init>(URLClassLoaderHelper.java:42) ~[?:?]
        at com.alessiodp.parties.core.common.addons.external.libby.BukkitLibraryManager.<init>(BukkitLibraryManager.java:28) ~[?:?]
        at com.alessiodp.parties.core.bukkit.bootstrap.ADPBukkitBootstrap.onEnable(ADPBukkitBootstrap.java:33) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:3043-Spigot-a25e8ed-9294ebb]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.5.jar:3043-Spigot-a25e8ed-9294ebb]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:3043-Spigot-a25e8ed-9294ebb]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:493) ~[spigot-1.16.5.jar:3043-Spigot-a25e8ed-9294ebb]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:407) ~[spigot-1.16.5.jar:3043-Spigot-a25e8ed-9294ebb]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:555) ~[spigot-1.16.5.jar:3043-Spigot-a25e8ed-9294ebb]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot-1.16.5.jar:3043-Spigot-a25e8ed-9294ebb]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5.jar:3043-Spigot-a25e8ed-9294ebb]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3043-Spigot-a25e8ed-9294ebb]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by AlessioDP** [comment]
Hello,
Java 16 is not supported due to problems with reflections, used in external library loading. Right now its not possible to support it, let's see in the future if Bukkit/BungeeCord will manually support loading of external libraries or I find a way to load them correctly in other ways :)
