### ISSUE TITLE
UnresolvedDependencyException

### ISSUE THREAD

**Issue by Tylwen** [AlessioDP/Parties#133]
[17:17:27] [Server thread/INFO]: [Parties] Loading Parties v3.1.8
[17:17:27] [Server thread/INFO]: [[36mParties[0m] Loading libraries of Parties v3.1.8, this may take a while
[17:17:27] [Server thread/WARN]: UnresolvedDependencyException{dependency=Dependency{groupId='me.lucko', artifactId='jar-relocator', version='1.4', snapshotId='null', transitive=[Dependency{groupId='org.ow2.asm', artifactId='asm', version='9.1', snapshotId='null', transitive=[]}, Dependency{groupId='org.ow2.asm', artifactId='asm-commons', version='9.1', snapshotId='null', transitive=[]}]}}
[17:17:27] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.lambda$download$0(URLDependencyDownloader.java:64)
[17:17:27] [Server thread/WARN]: 	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
[17:17:27] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.download(URLDependencyDownloader.java:64)
[17:17:27] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.injector.helper.InjectionHelper.fetch(InjectionHelper.java:45)
[17:17:27] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:56)
[17:17:27] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.inject(SimpleDependencyInjector.java:50)
[17:17:27] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.InjectingApplicationBuilder.build(InjectingApplicationBuilder.java:51)
[17:17:27] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.relocation.facade.ReflectiveJarRelocatorFacadeFactory.create(ReflectiveJarRelocatorFacadeFactory.java:126)
[17:17:27] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.relocation.facade.ReflectiveJarRelocatorFacadeFactory.create(ReflectiveJarRelocatorFacadeFactory.java:118)
[17:17:27] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.getRelocatorFactory(ApplicationBuilder.java:190)
[17:17:27] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.createInjector(ApplicationBuilder.java:276)
[17:17:27] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.InjectingApplicationBuilder.build(InjectingApplicationBuilder.java:50)
[17:17:27] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.ADPPlugin.loading(ADPPlugin.java:64)
[17:17:27] [Server thread/WARN]: 	at com.alessiodp.parties.core.bukkit.bootstrap.ADPBukkitBootstrap.onLoad(ADPBukkitBootstrap.java:29)
[17:17:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399)
[17:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269)
[17:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[17:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[17:17:27] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[17:17:27] [Server thread/ERROR]: [[36mParties[0m] Failed to load libraries, the plugin will be stopped

Minecraft Paper 1.16.5 779
Online server

**Comment by Tylwen** [comment]
I have already tested to install LastLoginAPI

**Comment by Tylwen** [comment]
And I just installed it so there was no file of this plugin and there is still none

**Comment by AlessioDP** [comment]
Its an issue with slimjar library, the developer is working on a fix.
