### ISSUE TITLE
Error at start

### ISSUE THREAD

**Issue by LuuckA21** [AlessioDP/Parties#142]
[02:03:25] [main/INFO]: [[36mParties[0m] Loading libraries of Parties v3.1.9, this may take a while
[02:03:27] [main/ERROR]: java.lang.NullPointerException: Cannot invoke "String.trim()" because "ownerHash" is null
[02:03:27] [main/ERROR]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.relocation.helper.VerifyingRelocationHelper.relocate(VerifyingRelocationHelper.java:61)
[02:03:27] [main/ERROR]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.injector.helper.InjectionHelper.fetch(InjectionHelper.java:49)
[02:03:27] [main/ERROR]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:56)
[02:03:27] [main/ERROR]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.inject(SimpleDependencyInjector.java:50)
[02:03:27] [main/ERROR]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.InjectingApplicationBuilder.buildApplication(InjectingApplicationBuilder.java:56)
[02:03:27] [main/ERROR]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.build(ApplicationBuilder.java:420)
[02:03:27] [main/ERROR]: 	at com.alessiodp.parties.core.common.ADPPlugin.loading(ADPPlugin.java:64)
[02:03:27] [main/ERROR]: 	at com.alessiodp.parties.core.bungeecord.bootstrap.ADPBungeeBootstrap.onLoad(ADPBungeeBootstrap.java:28)
[02:03:27] [main/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:398)
[02:03:27] [main/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300)
[02:03:27] [main/ERROR]: 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278)
[02:03:27] [main/ERROR]: 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[02:03:27] [main/ERROR]: 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[02:03:27] [main/ERROR]: [[36mParties[0m] Failed to load libraries, the plugin will be stopped

**Comment by AlessioDP** [comment]
Delete the folder plugins/Parties/libraries ;)
