### ISSUE TITLE
Can't initialization the plugin while download library

### ISSUE THREAD

**Issue by Mu-cream** [AlessioDP/Parties#227]
Can I download the library in other way?I'm on the Internet in China

**Comment by AlessioDP** [comment]
Libraries are required to work, if the server is not able to download them, you can install it on your computer and start a simple MC server. Once downloaded all libraries you can move the folder plugins/Parties into the server itself.

**Comment by Mu-cream** [comment]
> 

I'try to use proxy and run a server on local,but it still can't to download the library

**Comment by Mu-cream** [comment]
[Parties] Failed to initialize library manager
java.lang.ClassNotFoundException: me.lucko.jarrelocator.JarRelocator
        at java.net.URLClassLoader.findClass(URLClassLoader.java:440) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.loader.IsolatedInjectableClassLoader.loadClass(IsolatedInjectableClassLoader.java:67) ~[Parties-3.2.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.relocation.facade.ReflectiveJarRelocatorFacadeFactory.create(ReflectiveJarRelocatorFacadeFactory.java:128) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.relocation.facade.ReflectiveJarRelocatorFacadeFactory.create(ReflectiveJarRelocatorFacadeFactory.java:116) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.getRelocatorFactory(ApplicationBuilder.java:335) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.createInjector(ApplicationBuilder.java:445) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.InjectingApplicationBuilder.buildApplication(InjectingApplicationBuilder.java:60) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.build(ApplicationBuilder.java:462) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.libraries.LibraryManager.init(LibraryManager.java:40) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.ADPPlugin.loading(ADPPlugin.java:63) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.bukkit.bootstrap.ADPBukkitBootstrap.onLoad(ADPBukkitBootstrap.java:33) ~[Parties-3.2.9.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:20:00 ERROR]: [Parties] Failed to load libraries, the plugin will be stopped


is that a network problem?seems not

**Comment by AlessioDP** [comment]
Seems like the library was downloaded but corrupted (or empty), try to delete libraries folder and try again.

**Comment by Mu-cream** [comment]
> Seems like the library was downloaded but corrupted (or empty), try to delete libraries folder and try again.

ok,I'll try it

**Comment by Mu-cream** [comment]
> Seems like the library was downloaded but corrupted (or empty), try to delete libraries folder and try again.

oops,Still dead


[21:24:27 INFO]: [Parties] Downloading asm...
>
[21:25:02 ERROR]: [Parties] Failed to initialize library manager
com.alessiodp.parties.core.common.addons.external.slimjar.injector.InjectionFailedException: SlimJar failed to inject dependency: name -> org.ow2.asm:asm:9.1
        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:65) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:63) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.inject(SimpleDependencyInjector.java:52) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.InjectingApplicationBuilder.buildApplication(InjectingApplicationBuilder.java:65) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.build(ApplicationBuilder.java:462) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.relocation.facade.ReflectiveJarRelocatorFacadeFactory.create(ReflectiveJarRelocatorFacadeFactory.java:127) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.relocation.facade.ReflectiveJarRelocatorFacadeFactory.create(ReflectiveJarRelocatorFacadeFactory.java:116) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.getRelocatorFactory(ApplicationBuilder.java:335) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.createInjector(ApplicationBuilder.java:445) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.InjectingApplicationBuilder.buildApplication(InjectingApplicationBuilder.java:60) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.build(ApplicationBuilder.java:462) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.libraries.LibraryManager.init(LibraryManager.java:40) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.ADPPlugin.loading(ADPPlugin.java:63) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.bukkit.bootstrap.ADPBukkitBootstrap.onLoad(ADPBukkitBootstrap.java:33) ~[Parties-3.2.9.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.net.SocketException: Connection reset
        at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323) ~[?:?]
        at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
        at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
        at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.util.Connections.createDownloadConnection(Connections.java:43) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.download(URLDependencyDownloader.java:95) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.helper.InjectionHelper.fetch(InjectionHelper.java:45) ~[Parties-3.2.9.jar:?]
        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:58) ~[Parties-3.2.9.jar:?]
        ... 18 more
[21:25:02 ERROR]: [Parties] Failed to load libraries, the plugin will be stopped

**Comment by AlessioDP** [comment]
Probably doesn't work via only a proxy, did you try in a local server with a VPN itself? Otherwise there is no way to make it work, its not possible to make a single jar with all those libraries.

PS. The proxy/connection issue depends on Slimjar library, not Parties itself.

**Comment by Mu-cream** [comment]
> Probably doesn't work via only a proxy, did you try in a local server with a VPN itself? Otherwise there is no way to make it work, its not possible to make a single jar with all those libraries.
> 
> PS. The proxy/connection issue depends on Slimjar library, not Parties itself.

Thanks>I'll find other way to deal it :)
