### ISSUE TITLE
please fix this

### ISSUE THREAD

**Issue by successed** [AlessioDP/Parties#40]
[15:02:12 ERROR]: Could not pass event EntityDamageByEntityEvent to Parties v2.4.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-513]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-513]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-513]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-513]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:104) ~[patched_1.13.2.jar:git-Paper-513]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:834) ~[patched_1.13.2.jar:git-Paper-513]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:733) ~[patched_1.13.2.jar:git-Paper-513]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:866) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1520) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity0(EntityHuman.java:904) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:993) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:817) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:658) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1082) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1433) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2024) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-513]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-513]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_191]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_191]
        at com.alessiodp.parties.bukkit.parties.objects.BukkitPartyImpl.sendFriendlyFireWarn(BukkitPartyImpl.java:104) ~[?:?]
        at com.alessiodp.parties.bukkit.listeners.BukkitFightListener.onPlayerHit(BukkitFightListener.java:96) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor191.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-513]
        ... 26 more

**Comment by AlessioDP** [comment]
Do you have this problem with Parties 2.5.2?
Does it happen every time or just sometimes?

**Comment by AlessioDP** [comment]
Can you attach here your log of Parties 2.5.2 please.
