### ISSUE TITLE
Plugin does not enable

### ISSUE THREAD

**Issue by zainmz** [AlessioDP/Parties#79]
Using Version: Parties 3.0.0-rc.1
Server software: PaperSpigot 1.16.4

`>.... [09:18:34 ERROR]: Error occurred while enabling Parties v3.0.0-rc.2 (Is it up to date?)
java.lang.NullPointerException: permission is marked non-null but is null
at com.alessiodp.parties.core.common.commands.utils.ADPSubCommand.<init>(ADPSubCommand.java:13) ~[?:?]
at com.alessiodp.parties.common.commands.utils.PartiesSubCommand.<init>(PartiesSubCommand.java:18) ~[?:?]
at com.alessiodp.parties.bukkit.commands.sub.BukkitCommandConfirm.<init>(BukkitCommandConfirm.java:22) ~[?:?]
at com.alessiodp.parties.bukkit.commands.main.BukkitCommandParty.<init>(BukkitCommandParty.java:29) ~[?:?]
at com.alessiodp.parties.bukkit.commands.BukkitPartiesCommandManager.registerCommands(BukkitPartiesCommandManager.java:28) ~[?:?]
at com.alessiodp.parties.core.common.commands.CommandManager.setup(CommandManager.java:34) ~[?:?]
at com.alessiodp.parties.common.PartiesPlugin.postHandle(PartiesPlugin.java:78) ~[?:?]
at com.alessiodp.parties.bukkit.BukkitPartiesPlugin.postHandle(BukkitPartiesPlugin.java:67) ~[?:?]
at com.alessiodp.parties.core.common.ADPPlugin.enabling(ADPPlugin.java:64) ~[?:?]
at com.alessiodp.parties.core.bukkit.bootstrap.ADPBukkitBootstrap.onEnable(ADPBukkitBootstrap.java:34) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-345]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-345]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-345]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-345]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-345]
at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by AlessioDP** [comment]
Fixed with upcoming 3.0.0-rc.3.
